<?php

use Icinga\Application\Config;


// Requirements
global $config;

$config = Config::module('hardwareinfo');

$errors = array();

error_reporting(E_ALL ^ E_DEPRECATED);

$host = $config->get('db', 'host'); // имя хоста 
$database = $config->get('db', 'name'); // имя базы данных 
$user = $config->get('db', 'user'); // имя пользователя
$pswd = $config->get('db', 'password'); // пароль

$dbh = mysqli_connect($host, $user, $pswd, $database);

//$dbh = mysql_connect($host, $user, $pswd) or die("Не могу соединиться с MySQL.");
//mysql_select_db($database) or die("Не могу подключиться к базе.");
//mysql_query("SET names UTF8");

mysqli_query($dbh, "SET names UTF8");

########################################
$q_report = "SELECT tbComputerTarget.Name AS Host,
MAX(IF(PropertyID=23,Value, NULL)) AS OSVer,
MAX(IF(PropertyID=4,Value, NULL)) AS CPU,
MAX(IF(PropertyID=3,Value, NULL)) AS CPUSpeed,
MAX(IF(PropertyID=106,Value, NULL)) AS RAMCapacity,
MAX(IF(PropertyID=107,Value, NULL)) AS RAMSpeed,
MAX(IF((PropertyID=26 AND Value NOT Like '%USB%'),Value, NULL)) AS HDD,
MAX(IF((PropertyID=31 AND Value > 33000000000),Value, NULL)) AS HDDSize,
MAX(IF((PropertyID=62 AND (Value Like '%Realtek%' OR Value Like '%Atheros%' OR Value Like '%Marvell%' OR Value Like '%NVIDIA%')),Value, NULL)) AS Net,
MAX(IF(PropertyID=74,Value, NULL)) AS Video,
MAX(IF(PropertyID=75,Value, NULL)) AS VideoRAM,
MAX(IF(PropertyID=71,Value, NULL)) AS Sound
FROM tbComputerInventory INNER JOIN
tbComputerTarget ON tbComputerInventory.ComputerTargetId = tbComputerTarget.ComputerTargetId
GROUP BY tbComputerTarget.Name;";

$r_report = mysqli_query($dbh, $q_report)  or die(mysqli_error());


?>

<div class="controls">
<?= $this->tabs ?>
</div>
<div class="content">


<h1>Hosts</h1>

<?php

echo '<table data-base-target="_next" class="common-table"><tbody>';



while($row = mysqli_fetch_array($r_report)) {


    echo "<tr><td><a href='/icingaweb2/hardwareinfo/index/tree?q=".$row['Host']."'>".$row['Host']."</a></td></tr>";

}
echo '</tbody></table>';

?>


</div>



    
