<?php

use Icinga\Web\Url;

/** @var \Icinga\Web\View $this */
/** @var \Icinga\Web\Widget\FilterEditor $filterEditor */
/** @var \Icinga\Module\Monitoring\DataView\DataView $services */
/** @var \Icinga\Web\Url $hostBaseUrl */
/** @var \Icinga\Web\Url $serviceBaseUrl */



if (! $compact): ?>
<div class="controls">
    <?= $tabs ?>
    <?= $paginator ?>
    <div class="sort-controls-container">
        <?= $limiter ?>
        <?= $sortBox ?>
    </div>
    <?= $filterEditor ?>

</div>
<?php endif ?>




<div class="content">

<?php

if ($hosts->hasResult()) {

    echo '<table data-base-target="_next" class="hardwareinfo-state-table state-table table-row-selectable" >';

    echo '<thead><tr>
        <th>'.$this->translate('State').'</th>
        <th>'.$this->translate('Host Name').'</th>
        <th>'.$this->translate('Host OS').'</th>
        <th>'.$this->translate('HW Model').'</th>
        <th>'.$this->translate('Host CPU').'</th>
        <th>'.$this->translate('Host RAM').'</th>
        </tr></thead>
        <tbody>';


    foreach ($hosts->peekAhead($compact) as $host) {

        if ($host->host_state == 0) {
            $class_state = "state-up";
            $label_state = "UP";
            $plugin_output = $this->translate('Zone is connected.');

        } elseif ($host->host_state == 1) {
            $class_state = "state-down";
            $label_state = "DOWN";
            $plugin_output = $this->translate('Zone is not connected.');

        } else {
            $class_state = "state-unreachable";
            $label_state = "UNREACHABLE";
            $plugin_output = $this->translate('Unknown');


        }

        $titleHostLink = $this->translate('Show detailed information for host ').$host->host_name;
        $titleHWLink = $this->translate('Show hardware information for host ').$host->host_name;



        $hostLink = $this->qlink($host->host_name, $hostBaseUrl."/monitoring/host/show?host=".$host->host_name, null, [
                'class'             => '',
                'title'  => $titleHostLink,
                'data-base-target'  => '_next'
            ]);
        $hardwareInfoLink = $this->qlink("Hardware Information", $hostBaseUrl."/hardwareinfo/tree?host=".$host->host_name, null, [
                'class'             => 'rowaction', //action-link
                'title'        => $titleHWLink,
                'data-base-target'  => '_next'
            ]);

echo '<tr>
    <td class="state-col '.$class_state.'">
        <div class="state-label">'.$label_state.'</div>
        <div class="state-meta">
            <span class="relative-time time-since" title=""></span>
        </div>
    </td>
    <td>
        <div class="state-header">'
    .$this->img($host->host_icon_image, null, []).$hostLink.': '.$hardwareInfoLink.'</div>
        <p class="overview-plugin-output">'.$plugin_output.'</p>
    </td>
    <td>
        <p class="vars-os">'
        .$host->os
        .'</p>
    </td>
    <td>
        <p class="vars-hw">'
        .$host->manufacturer.'<br>'
        .$host->model
        .'</p>
    </td>
    <td>
        '.$host->cpu.'
    </td>
    <td>
        '.$host->ram.'
    </td>
</tr>';

    }


    echo '</tbody></table>';


} else {
    echo '<p>' . $this->escape(mt('monitoring', 'No hosts found matching the filter.')) . '</p>';
}


?>




</div>
