<?php

use Icinga\Web\Url;

/** @var \Icinga\Web\View $this */
/** @var \Icinga\Web\Widget\FilterEditor $filterEditor */
/** @var \Icinga\Module\Monitoring\DataView\DataView $services */
/** @var \Icinga\Web\Url $hostBaseUrl */
/** @var \Icinga\Web\Url $serviceBaseUrl */


?>


<div class="controls">
<?= $this->tabs ?>
</div>

<div class="content">

    <div style="width: 100%;">
        <h1><?php echo $this->translate('Hardware Information') ?></h1>
        <div class="treesearch">
            <div class="filter icinga-controls">
                <form method="post" class="search inline">
                    <input type="text" id="jstreehtml_q" name="q" style="width: 8em;padding-left: 18px;" class="search" value="" placeholder="Search...">
                </form>
            </div>
        </div>
        <br>
        <div id="jstreehtml" class="">

<?php
echo $r_AllClass;

?>

        </div>
    </div>


</div>




<style>
.vakata-context {
    z-index: 100000;
}
</style>

<script type="text/javascript">
$(function () {
  $("#jstreehtml").jstree({
    "types" : {
            "default" : {
            "icon" : "jstree-file"
        }
    },
    // "contextmenu" : {
    //     "items" : function($node) {
    //         return {
    //             "Create": {
    //                 "separator_before": false,
    //                 "separator_after": false,
    //                 "icon": false,
    //                 "label": "Copy value",
    //                 "action": function (obj) {
    //                     var cpValue = $node.text;
    //                     console.log(cpValue);

    //                     //Копирование в буфер обмена на чистом JavaScript
    //                     // Create new element
    //                     var el = document.createElement('textarea');
    //                     // Set value (string to be copied)
    //                     el.value = cpValue;
    //                     // Set non-editable to avoid focus and move outside of view
    //                     el.setAttribute('readonly', '');
    //                     el.style = {position: 'absolute', left: '-9999px'};
    //                     document.body.appendChild(el);
    //                     // Select text inside element
    //                     el.select();
    //                     // Copy text to clipboard
    //                     document.execCommand('copy');
    //                     // Remove temporary element
    //                     document.body.removeChild(el);
    //                 }
    //             }
    //         };
    //     }
    // },
    // "plugins" : [ "types", "search", "contextmenu" ]
    "plugins" : [ "types", "search" ]
  });
  var to = false;
  $('#jstreehtml_q').keyup(function () {
    if(to) { clearTimeout(to); }
    to = setTimeout(function () {
      var v = $('#jstreehtml_q').val();
      $('#jstreehtml').jstree(true).search(v);
    }, 250);
  });
});
// $('.vakata-context').css('z-index', 10000);

</script>
