<?php

use Icinga\Web\Url;

/** @var \Icinga\Web\View $this */
/** @var \Icinga\Web\Widget\FilterEditor $filterEditor */
/** @var \Icinga\Module\Monitoring\DataView\DataView $services */
/** @var \Icinga\Web\Url $hostBaseUrl */
/** @var \Icinga\Web\Url $serviceBaseUrl */


?>


<div class="controls">
<?= $this->tabs ?>
</div>

<div class="content">

    <div style="width: 100%;">
        <h1><?php echo $this->translate('Hardware Information') ?></h1>
        <div class="treesearch">
            <input type="text" id="jstreehtml_q" name="q" style="width: 8em" class="search" value="" placeholder="Search...">
        </div>
        <br>
        <div id="jstreehtml" class="">

<?php
echo $r_AllClass;

?>

        </div>
    </div>


</div>





<script type="text/javascript">
$(function () {
  $("#jstreehtml").jstree({
    "types" : {
            "default" : {
            "icon" : "jstree-file"
        }
    },
    "plugins" : [ "types", "search" ]
  });
  var to = false;
  $('#jstreehtml_q').keyup(function () {
    if(to) { clearTimeout(to); }
    to = setTimeout(function () {
      var v = $('#jstreehtml_q').val();
      $('#jstreehtml').jstree(true).search(v);
    }, 250);
  });
});

</script>
